# Generated by Django 5.0.3 on 2024-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode", models.CharField(max_length=20, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
